### ISSUE TITLE
Bind option or select value to model

### ISSUE THREAD

**Issue by switz** [derbyjs/derby#146]
I have three select objects:

```
<select name="month" x-bind="change: date.update">
      {#each _validateVideos.months as :month}
        <option value="{:month}" selected="{equal(:month, :video.showDate.month)}">{:month}</option>
      {/each}
    </select> / 
    <select name="day" x-bind="change: date.update">
      {#each _validateVideos.days as :day}
        <option value="{:day}" selected="{equal(:day, :video.showDate.day)}">{:day}</option>
      {/each}
    </select> / 
    <select name="year" x-bind="change: date.update">
      {#each _validateVideos.years as :year}
        <option value="{:year}" selected="{equal(:year, :video.showDate.year)}">{:year}</option>
      {/each}
    </select>
```

I want to bind all three to a value so I can access it in the `x-bind="change: date.update"` function. Is there any way of completing this?

From the derby website:

> Binding the selected attribute of <option> elements in a <select> is difficult, because the change event is only fired on the <select> element, and the selected attribute must be place on the options. Therefore, Derby distributes the change event to each of the children of a select element, raising the event on each of the options as well. This makes it possible to bind the selected state on each of the options.

This makes the event call on each individual option, but there's still no way of accessing the two other select elements. I could set each one on change, but is there a way to bind them all directly to a local derby model?

**Comment by curran** [comment]
Updated link: https://github.com/derbyjs/derby-examples/blob/master/sink/views/home.html#L21
