### ISSUE TITLE
Issue with Head: template part and custom styles

### ISSUE THREAD

**Issue by richtera** [derbyjs/derby#223]
When trying to insert custom CSS it's sometimes important to be able to insert custom styles before or after the auto compiled stylus or less styles. For example when adding:

``` html
  <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="css/font-awesome-ie7.css"/>
  <![endif]-->
```

Not being able to force positioning of the <style id="$_css"/> many times requires all styles to be inserted manually because of this. I was thinking it might be good to have a tag to include those styles like head:styles/. If not found then it can be added at the end.
Should I put together a pull request for something like this or is this considered a bad idea?

**Comment by curran** [comment]
Is there a way to have the compiled styles loaded after styles loaded from a CDN? For example, I'd like to include Bootstrap from a CDN, then have my custom styles override certain things.

As an example, here's what I'm seeing when I "view source" on one of my pages (formatted for readability):

```
<style data-filename="/Users/curran/repos/test/apps/app/styles">
  .logo-image {
    display: inline-block;
    padding-right: 5px;
  }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css">
```

However, what I'd ideally want is the following:

```
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css">
<style data-filename="/Users/curran/repos/test/apps/app/styles">
  .logo-image {
    display: inline-block;
    padding-right: 5px;
  }
</style>
```

Is there any hook for telling Derby where in the `<head>` to load the compiled styles? From what I can see, Derby always includes the compiled styles as the first thing in the `<head>`. It would be great to have a way of modifying this.

@nateps Really appreciate all your work on Derby!
