### ISSUE TITLE
History not updated

### ISSUE THREAD

**Issue by paglias** [derbyjs/derby#287]
History.md (https://github.com/codeparty/derby/blob/master/History.md) has not been updated since 0.3.14

**Comment by curran** [comment]
It would be nice to know what changes in each release. Perhaps the best way would be to add notes to the actual release tags in GitHub? If you go here https://github.com/derbyjs/derby/releases/tag/v0.8.5 , there is an nice UI in GitHub for adding a text description to the tag.

**Comment by craigbeck** [comment]
Thnaks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
