### ISSUE TITLE
gh-pages branch not up to date with reality

### ISSUE THREAD

**Issue by cjblomqvist** [derbyjs/derby#302]
Which makes it difficult to create PRs to help keep them up to date. Or am I missing something?

**Comment by craigbeck** [comment]
Thnaks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

Our current plan is to make a significant pass to update the docs at https://derbyjs.github.io/derby/
