### ISSUE TITLE
Objects added to a collection lose date property values

### ISSUE THREAD

**Issue by psirenny** [derbyjs/derby#304]
``` javascript
model.add('objects', {
  date: new Date(),
  name: 'some object'
});
```

Creates the following object in mongo:

``` javascript
{
  date: {}, // empty object instead of iso string
  id: '...',
  name: 'some object'
}
```

`model.set('objects.<id>.date', new Date())` works correctly.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
