### ISSUE TITLE
model.on() server side rendering

### ISSUE THREAD

**Issue by ile** [derbyjs/derby#328]
Can't get model.on() to work when it's run on server side. 

Code:

``` coffeescript
app.get '/link', (page, model, params, next) ->
  model.on 'change', '_page.this.that', (captures) ->
    console.log captures

  ...

```

The callback above isn't ever run if the route `/link` is rendered on server side (F5 on browser). It works ok if it's rendered client side.

Is this a bug or am I missing something? Any workarounds?

**Comment by curran** [comment]
Here's the link to the related discussion on the mailing list https://groups.google.com/forum/#!topic/derbyjs/AmXi6_vBzC0
