### ISSUE TITLE
Use websockets for real time synchronization

### ISSUE THREAD

**Issue by same79alal** [derbyjs/derby#372]
from derby website( http://derbyjs.com/#deploy_to_heroku ):
"Note that while Derby supports multiple servers, it currently requires that clients repeatedly connect to the same server. Heroku does not support sticky sessions or WebSockets, so it isn’t possible to use more than one dyno. You’ll have to use a different hosting option to scale your app."

Now Heroku finally supports websockets:
https://devcenter.heroku.com/articles/heroku-labs-websockets
https://blog.heroku.com/archives/2013/10/8/websockets-public-beta
https://devcenter.heroku.com/articles/node-websockets

However the browser channel depends on sticky sessions instead for its implementation as detailed in https://github.com/josephg/node-browserchannel/issues/32 which is not supported on heroku

Is there any plans for Derby to support websockets in the future?

Thanks!

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
