### ISSUE TITLE
[0.6] Client-side render error on Safari/iOS

### ISSUE THREAD

**Issue by cray0000** [derbyjs/derby#386]
Client-side rendering doesn't work in Safari/iOS. It throws an error

```
HIERARCHY_REQUEST_ERR: DOM Exception 3: A Node was inserted somewhere it doesn't belong.
```

It happens inside the `Page.js` in `Page.prototype.render` on the render line:

```
document.replaceChild(fragment, document.documentElement);
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

Looks like this issue targets several out of date version sof softwares (iOS, Safari). If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
