### ISSUE TITLE
[0.6] Cannot find view "node_modules\d-connection-alert"

### ISSUE THREAD

**Issue by icaliman** [derbyjs/derby#403]
I am getting this error in browser in all <code>derby-examples</code> that use <code>d-connection-alert</code> component:

<pre>
Uncaught Error: Cannot find view "node_modules\d-connection-alert" in
  Page
  Title
  Styles
  Head
  Body
  todo
  F:\Programare\Node.JS\derby-0.6\derby-examples\todos
  d-connection-alert
 components.js:175
</pre>

If I run todos example, in the generated script from <code>http://localhost:3000/derby/todos</code> I see that <code>__dirname</code> for components is in windows path format.
Here you can see some code from <code>http://localhost:3000/derby/todos</code>:

<pre>
...
(function (__dirname){
module.exports = ConnectionAlert;
function ConnectionAlert() {}
ConnectionAlert.prototype.view = __dirname;
...
}).call(this,"/node_modules\\d-connection-alert")
...
</pre>

Because __dirname is in windows format [here](https://github.com/codeparty/derby/blob/master/lib/components.js#L158) <code>path</code> module returns incorrect <code>basename</code>.
For <b>"/node_modules\d-connection-alert"</b> it returns <b>"node_modules\d-connection-alert"</b> instead of <b>"d-connection-alert"</b>.

When I change in debugger <code>__dirname</code> to be <code>/node_modules/d-connection-alert</code> path module returns <code>d-connection-alert</code> as basename and it works as expected.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
