### ISSUE TITLE
Component attribute binding

### ISSUE THREAD

**Issue by icaliman** [derbyjs/derby#410]
In this code:

``` html
<view name="list-component" list="{{_page.lists[selectedItem.id]}}" />
```

I have to pass to `list-component` a list of elements at `_page.lists[selectedItem.id]`.
On page load the component gets a default list and is rendered ok. But if I change `selectedItem` the component is not re-rendered.

I tried this but it also doesn't work:

``` html
{{with selectedItem}}
  <view name="list-component" list="{{_page.lists[this.id]}}" />
{{/}}
```

Only this worked, but it is not so fast:

``` html
{{each items as #item}}
  {{if #item === selectedItem}}
    <view name="list-component" list="{{_page.lists[#item.id]}}" />
  {{/if}}
{{/each}}
```

**Comment by cjblomqvist** [comment]
This would be a nice bug the get fixed +1

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
