### ISSUE TITLE
Both components output the same template

### ISSUE THREAD

**Issue by james-bay** [derbyjs/derby#413]
Both components (`<first>` and `<second>`) output the same template
`<div>Second Component</div>`
Project that reproduces the problem
https://github.com/james-bay/first-project

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
