### ISSUE TITLE
 Cannot call method 'make' of undefined

### ISSUE THREAD

**Issue by KnowledgeGarden** [derbyjs/derby#424]
Using code from the sketch at the derbyjs homepage, I start here:
var app = require('derby').createApp(module);
app.use(require('d-bootstrap'));
app.view.make('Body',
  'Holler: <input value="{hello.message}"><h1>{hello.message}</h1>'
);

A console.log on app.view returns undefined.
A console log on app.views returns [object, Object]

Removing 'd-bootstrap' changed nothing.
Is this some sort of version problem? If so, where can I find a more recent tutorial on bringing up Derby with Bootstrap?
Thanks.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
