### ISSUE TITLE
Items order is broken in each block

### ISSUE THREAD

**Issue by icaliman** [derbyjs/derby#430]
I have a list of items:

```
{{each logs as #log}}
  {{if #log.visible}}
    <p>
      #log.message
    </p>
  {{/}}
{{/}}
```

Sometimes I need to insert new items at position 0:

``` coffee
@socket.on 'new_log', (log) =>
  model.insert "logs", 0,
    message: log
    visible: @filterLog(log)
```

If all items have setted `visible=true` then new items are inserted in html at right position, but if some items have `visible=false` then new items are inserted in wrong place.

Here is a video showing the issue: http://youtu.be/dMHNR-MwhZQ

If you think it's an issue in my code, I can publish it, but I don't think. :)

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
