### ISSUE TITLE
Add static (render-persistent) html elements

### ISSUE THREAD

**Issue by droganov** [derbyjs/derby#447]
Hello.
This is a feature request. 

I would like derby to support render-persistent blocks on the page, witch would survive during page reloads.

Example cases are:
- Music player
- Video player
- Video chat

I would like to allow user to navigate the application while watching the video etc....

I'm not familiar how derby's render actually works, but I guess that could be done in the next way:

```
{{ static "blockName" }}
block code
{{ / }}
```

Derby's render probably could detach elements from the page, in the way jquery `detach()`does and then attach them after page renders.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
