### ISSUE TITLE
Count doesn't updade after change

### ISSUE THREAD

**Issue by droganov** [derbyjs/derby#448]
Hello, 

Here is the code:

```
q = model.query "posts", 
    $count: true
    $query:
        $and: [
            _user: _user
            visible: false
        ]
    model.subscribe q, (err) =>
        return cb err if err
        q.refExtra "_page.observe.drafts"
        model.on "change", "_page.observe.drafts", =>
            # create a new draft if no drafts
        cb()
```

Let's assume we have one draft post. Counter will output 1 in template even though g.get() gives us an empty array and not 1 as expected. Then user makes a post, and draft becomes visible. Counter will still show 1 however there is no more drafts in collection, so we won't catch model update event to create a new draft.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
