### ISSUE TITLE
model.del not catching by {{each}} in inserted component in other component

### ISSUE THREAD

**Issue by russll** [derbyjs/derby#453]
demo of bug - http://github.com/onerussell/derby-example-todo-components
1.open localhost:3000/gallery
2.create 10 todos
3.delete third todo
4.third todo disappear but last todo component is empty

 think the bug is related to the index in the array

**Comment by aliksend** [comment]
I think that [it is the same](https://github.com/derbyparty/derby-faq/issues/42)

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
