### ISSUE TITLE
Memory Leaks: components not being destroyed after manual app.page.render() on client

### ISSUE THREAD

**Issue by cray0000** [derbyjs/derby#454]
Hi, there is a pretty common usecase for a web-app to **change current view but leave the model untouched**. The solution seems to be this -- use **app.page.render(ns)** on the client side to load another view on demand.

But there is the same issue as in #414 -- components are not being destroyed after they are rendered over. 
Is it a bug or app.page.render() should not be used after initial rendening by controller?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
