### ISSUE TITLE
Passing a view name to a view with {{$render.prefix}} fails

### ISSUE THREAD

**Issue by psirenny** [derbyjs/derby#457]
If you try to pass a view name to a view with $render.prefix it will fail with:

```
TypeError: Object #<Template> has no method 'split'
```

For example:

```
<something:>
  <view name="foo" pass="{{$render.prefix}}bar"></view>

<foo:>
  <view name="{{@pass}}></view>

<bar:>
  <p>text</p>
```

You receive a similar error if you recursively try to pass a view name more than one level deep (without the $render.prefix of course).

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
