### ISSUE TITLE
error when {{unescaped data}} in component, data is svg element

### ISSUE THREAD

**Issue by russll** [derbyjs/derby#461]
it's bug or feature request?
it's my test component for this trouble:
//////////////////////////////////////////////////////////////
index.html

<div style="width:{{width}}px;height:{{height}}px;">]
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {{width}} {{height}}" width="{{width}}" height="{{height}}" preserveAspectRatio="xMidYMid meet">
            {{unescaped data}}
        </svg>
</div>

//////////////////////////////////////////////////////////////
index.js

function Component() {}

module.exports = Component;

Component.prototype.view = __dirname;

Component.prototype.init = function() {
    this.model.setNull('data', '<g class="add"><path d="M19,13h-6v6h-2v-6H5v-2h6V5h2v6h6V13z"/></g>');
    this.model.setNull('width', '25');
    this.model.setNull('height', '25');
}
/////////////////////////////////////////////////////////////
i get trouble(this is not a critical but error in console is no good)
in this:
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {{width}} {{height}}" width="{{width}}" height="{{height}}" preserveAspectRatio="xMidYMid meet">
            {{unescaped unbound data}}
        </svg>
i get this trace()
at Error (native)
    at createHtmlFragment 
    at Template.DynamicHtml.appendTo 
    at appendContent 
    at Template.Element.appendTo 
    at appendContent 
    at Template.ConditionalBlock.appendTo 
    at appendContent 
    at Template.Element.appendTo 

i get error:

Uncaught NotSupportedError: Failed to execute 'createContextualFragment' on 'Range': The range's container must be an HTML element. events.js:59
EventEmitter.emitevents.js:59
App._finishInitApp.js:88
(anonymous function)App.js:119

i think it is a bug, in interaction derby with svg nodes

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
