### ISSUE TITLE
Component name has to be lower-case letters.

### ISSUE THREAD

**Issue by LarsBV** [derbyjs/derby#466]
Component.html

```
<index: element="AutoForm">
   <!--- some code --->
```

JS:

```
AutoForm.prototype.show = function() {}
```

Template:

```
<AutoForm as="foobar"></AutoForm>
<button on-click="foobar">Click</button
```

this results in a error, no such function.

But it works with all lower-case letters.

ps: Thanks a lot for a very impressive library :)

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
