### ISSUE TITLE
Issue with parsing commented out templates at the end of an HTML file

### ISSUE THREAD

**Issue by dadisn** [derbyjs/derby#468]
When a parsing an HTML view file that contains a commented out template (i.e. `<template:>`) at the end of the file, the only thing that gets rendered in the browser is a single greater-than sign (i.e. `>`, see image below). This does not happen when the comment at the end of the file does not contain a template definition.

![screenshot 2014-10-30 16 41 00](https://cloud.githubusercontent.com/assets/3164519/4846344/3b1662ba-604b-11e4-9091-40ad861eb1ce.png)

To recreate the bug the following stripped down Derby app code can be used:

index.js

``` javascript
var derby = require('derby')
  , app = module.exports = derby.createApp('demo-app', __filename)
    ;

app.loadViews(__dirname);

app.get('/', function(page, model, params, next) {
  page.render();
});
```

index.html

``` html
<Body:>
  <p>This is a test</p>

<!--
<randomTemplate:>
  <p>This is a random template.</p>
-->
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
