### ISSUE TITLE
EBUSY error on view/template change.

### ISSUE THREAD

**Issue by ruimgoncalves** [derbyjs/derby#470]
Hi

I'm using Windows 8.1 with Sublime for my dev environment. I have used derby-patch to workaround some windows related issues, and as far as I can tell, they work for me.

But when I save some change on a html view file, the server crashes with an error. :bug:

> Error: EBUSY, resource busy or locked ...

The file seems to be in use when you call app.loadViews.
I made some alterations to prevent this in the App.server.js file but I think the problem resides in chokidar, and the way it handles fs events in windows systems.

``` javascript
App.prototype._watchViews = function(filenames, filename, namespace) {
  var app = this;
  var watcher = chokidar.watch(filenames);
  watcher.on('change', function() {
    watcher.close();
    setTimeout(function() {
      app.loadViews(filename, namespace);
      app._updateScriptViews();
      app._refreshClients();
    }, 200);
  });
};
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
