### ISSUE TITLE
derby-examples: Hello. Don't work in IE9

### ISSUE THREAD

**Issue by MrEfrem** [derbyjs/derby#471]
Delete characters from the field backspace key is not synchronized with the displayed value.

**Comment by MrEfrem** [comment]
The project died?

**Comment by rdewolff** [comment]
Don't think project died. Did you try on https://gitter.im/derbyjs/derby ?

**Comment by MrEfrem** [comment]
And sense? If it doesn't work and who isn't going to correct. 1 person probably is engaged in support also that in off-duty time. Here quicker meteor will correct the defects which are well realized in derby, than derby will move a little.
