### ISSUE TITLE
Proposal about classes

### ISSUE THREAD

**Issue by kogarashisan** [derbyjs/derby#475]
Hello! I see, that you care about speed, so you write your classes by hands.
May I propose you my framework's ClassManager - it generates classes, that are as fast as their hand-written analogues.

Here is the speed comparison:
http://jsperf.com/liquidlava-class-system-performance/6

And here is the framework:
http://www.lava-framework.com/

If you like it - then please, star me on GitHub. I need stars to get listed at javascripting.com.
If you have questions - feel free to ask me.

**Comment by kogarashisan** [comment]
This issue is still open, so I will allow myself to add another comment.

My ClassManager now lives in a separate repository and already has 25 stars:
https://github.com/kogarashisan/ClassManager/

And here are updated performance tests with explanation:
https://github.com/kogarashisan/PerfTests

**Comment by aliksend** [comment]
Or you can just [use coffeescript](http://coffeescript.org/#classes)

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
