### ISSUE TITLE
Sometimes bindings like obj[@attr] don't work

### ISSUE THREAD

**Issue by mrThomasTeller** [derbyjs/derby#478]
I understood that when I use view attribute as object key or array index in binding, and this attribute referred to some path binding doesn't work. Bug is reproduced here: http://jsfiddle.net/mrThomasTeller/e125rkvb/11/
It's funny that if I wrap binding by "with" block and use #attr instead of @attr it works as intended.

**Comment by mrThomasTeller** [comment]
I've updated derby. Bug is still reproduced. http://jsfiddle.net/mrThomasTeller/e125rkvb/5/

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
