### ISSUE TITLE
Redundant rerendering of "each" block content

### ISSUE THREAD

**Issue by mrThomasTeller** [derbyjs/derby#479]
Please see this case to understand the issue http://jsfiddle.net/mrThomasTeller/e125rkvb/10/
Case:
1. We have an "each" block in a "conditional" block
2. We set items for the "each" block in the component "init" method using the component model "set" method
3. First time condition is false, so each block isn't rendered
4. When we change condition "each" block renders its content twice (renders first time, removes elements, renders second time the same elements)
If the "each" block contains views associated with components it destroys these components. So we get unexpected destructions.

**Comment by mrThomasTeller** [comment]
I've updated derby. Bug is still reproduced. http://jsfiddle.net/mrThomasTeller/e125rkvb/4/

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
