### ISSUE TITLE
Model.ref performance issue

### ISSUE THREAD

**Issue by xscheiner** [derbyjs/derby#484]
The code below is a piece of middleware that sets some basic user data in the model on every request.

``` javascript
   if (req.isAuthenticated()) {
      debug('authenticated');
      $user = model.at(options.collection + '.' + userId);
      $publicUser = model.at(options.publicCollection + '.' + userId);
      model.fetch($user, $publicUser, function(err) {
        model.set('_session.loggedIn', true);
        model.ref('_session.user', $publicUser);
        model.unfetch($user, next);
      });
    }
```

I was testing various scenarios when I found that if I submitted two login requests simultaneously, one of them would fail every time. The reason was this statement:

``` javascript
model.ref('_session.user', $publicUser);
```

$publicUser and $user were both set correctly on every request. But on the failing requests, _session.user would not be set and subsequent gets would return undefined.

I fixed the problem by using:

``` javascript
model.set('_session.user', model.get(options.publicCollection + '.' + userId));
```

My question is why .ref failed silently like that and of course why it failed at all. Two simultaneous requests is not a lot. Interestingly, BTW, the code worked on a more powerful environment. My guess is that that is because Model.ref is synchronous and thus blocking.

So the issue is:

  -- Model.ref fails on two simultaneous requests
  -- Model.ref fails silently

While I am at it, it would be interesting to understand better why one uses ref as opposed to set. I inherited the code above and so I don't know why ref was used in that particular case.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
