### ISSUE TITLE
analogue transition routes derby 0.6

### ISSUE THREAD

**Issue by desnet** [derbyjs/derby#486]
Need an analogue of the transition routes such as in derby 0.5

**Comment by enjalot** [comment]
i will answer this question in the mailing list

**Comment by desnet** [comment]
I did as you said, but the application terminates with an error message "derby-router: you should provide name or path to the route". It seems that the derby router is not able to do so. The documentation is not written anything about it. https://github.com/derbyparty/derby-router/blob/master/README.md

**Comment by zag2art** [comment]
Just don't use `derby-router` module. Use default derby router.

**Comment by desnet** [comment]
It works. generator-derby generates code using derby-router module. I plan to implement several major projects for the derby. I would like to participate in the development of the derby, I'm interested in this project. What do I need for this? Thank U.

**Comment by enjalot** [comment]
Glad to hear it. join one of the community chats: http://derbyjs.com/resources
we also do office hours every week: https://ma.lever.co/open-source-office-hours-jan-28-2015/ (See regular times at the bottom)
