### ISSUE TITLE
Is there a way to skip bundling for a faster restart?

### ISSUE THREAD

**Issue by rasteiner** [derbyjs/derby#495]
It would be really nice if the browserify / bundling step could be skipped, for example when the server crashes and `forever` or `pm2` or `whatever` restarts the app. The bundling can take quite a lot of time, especially when in `NODE_ENV=production` mode.

I'm talking about simly reusing the latest bundled .js file.

**Comment by rasteiner** [comment]
I just realized that this is more a `/derbyparty/generator-derby` issue.

**Comment by zag2art** [comment]
Yes, it's possble. If you ask me in the generator-derby I will answer how :)

**Comment by rasteiner** [comment]
@zag2art Thanks:

https://github.com/derbyparty/generator-derby/issues/32
