### ISSUE TITLE
IMG tags break Internet Explorer 11

### ISSUE THREAD

**Issue by rasteiner** [derbyjs/derby#496]
In Internet Explorer 11 (didn't try the older ones), clicking on any image that has a `src` which starts with `/`, behaves like there is a link on the image, pointing to the image.

Reproduce:

```
git clone https://github.com/rasteiner/iekittentest
cd iekittentest
npm i
npm start
```

open `http://localhost:3000` in IE11, click on the kitten and look at the address bar.

The test app is nothing more than a "yo derby:mini" with a kitten.jpg and an `img` tag.

PS: I've noticed that an external image file (eg: `http://lorempixel.com/100/100`) works correctly.
PPS: I have no clue where this is coming from, so I'm posting this here, since it's seems like a rather severe issue.

**Comment by rasteiner** [comment]
The cause might be that IE puts a "href" property to img tags. This line here seems suspicious: https://github.com/derbyjs/tracks/blob/master/lib/History.js#L156

**Comment by rasteiner** [comment]
This isn't just me using the framework wrong. This is the framework having a rather serious bug in one of the main browsers.

One of the "derby used in production" sites: 
http://gameofbombs.com/community/topic/669dd3f3-3d89-421a-b8cb-b6a13f9f0a91?page=1 
click on any avatar image in IE11.

This also makes it essentially impossible to put an image into a link, since the "imaginary link"s click event fires first and doesn't even bubble to the "real link".

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
