### ISSUE TITLE
binding issue with dynamic attribute lookup

### ISSUE THREAD

**Issue by enjalot** [derbyjs/derby#498]
when passing in an object to a component and then looking it up inside of an `each` like:

```
 {{@object[#i]}}
```

standalone repro case:
http://codepen.io/enjalot/pen/ragXex?editors=101

**Comment by ericyhwang** [comment]
Possibly related to https://github.com/derbyjs/derby/issues/478 ?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
