### ISSUE TITLE
class="{{undefined}}" results in class="null" during updates, inconsistent w/ initial rendering

### ISSUE THREAD

**Issue by ericyhwang** [derbyjs/derby#500]
During initial rendering, `<div class="{{undefined}}"></div>` results in `<div></div>`, where the `class` attribute isn't set at all.

On updates, `<div class="{{undefined}}"></div>` results in `<div class="null"></div>`, which is plain wrong.

Repro with derby-standalone is here, though I've also reproed with full server/client Derby:
http://codepen.io/anon/pen/MYMpyg?editors=101

The issue also occurs with `id`, `title`, `tabindex`, and any of the other attributes here whose mapped properties are non-boolean:
https://github.com/derbyjs/saddle/blob/f169078c6bb7f2ba1f75c43fb48be08b7388885f/index.js#L11

I think that the fix will be to fall-through to the `element.removeAttribute` block here, if the value is null and the property is non-boolean:
https://github.com/derbyjs/saddle/blob/f169078c6bb7f2ba1f75c43fb48be08b7388885f/index.js#L453

I'll see if I can get a repro in the Saddle tests and then get a fix proposed.

**Comment by ericyhwang** [comment]
Initial rendering flow skips setting the attribute/property if the value is null:
https://github.com/derbyjs/saddle/blob/f169078c6bb7f2ba1f75c43fb48be08b7388885f/index.js#L534

**Comment by craigbeck** [comment]
Thnaks for your contributing your issue.

We have recently been actively updating the Derby and Racer packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue sitll matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
