### ISSUE TITLE
querySelector not working

### ISSUE THREAD

**Issue by ChrisSG** [derbyjs/derby#507]
Hi,

for me querySelector in App.js (line 166 and 223) does not work and thus the live-refresh in devmode is not woring. It returns null... I replaced it with a the following function:

``` javascript
App.prototype.selectElement = function (elementName, attribute, value){
  var items = document.getElementsByTagName(elementName);
  var element = null;
  for(var i = 0; i < items.length; i++) {
    if (items[i].getAttribute(attribute).indexOf(value) == 0) {
      element = items[i]
      break;
    }
  }
  return element;
};
```

Respectively calling: 
166 return this.selectElement('script','src','/derby/' + this.name)
223 var styleElement = app.selectElement('style','data-filename',data.filename);

Regards,

Chris

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
