### ISSUE TITLE
Can I subscribe to $aggregate query?

### ISSUE THREAD

**Issue by aliksend** [derbyjs/derby#511]
I'm using an aggregate query to count images in cards. It is like this:
```
var imagesCount = model.query('users', {
  $aggregate: [
    { $match: {
        images: { $type: 3 },
        _type: {$ne: null }
      }
    }, {
      $group: {
        _id: null,
        value: {
          $sum: {
            $size: '$images'
          }
        }
      }
    }
  ]
});
```
And it is working good while I'm not trying to change `users` (insert or delete item).
I have a little sample, can't share using derby-standalone and codepen 'cos queries, but can upload and attach, but I think that you're understood me

PS I'm think that it is like [this issue](https://github.com/derbyjs/derby/issues/448)

**Comment by zag2art** [comment]
At the moment livedb-mongo doesn't support the featue - look here - https://github.com/share/livedb-mongo/blob/master/index.js#L466-L472
but you can fork it and add the line `query.hasOwnProperty('$aggregate') ||`

**Comment by aliksend** [comment]
Thank you. After refactoring I've been changed this code and added another `images` collection. I think that it is a better way than this big and terrible `$aggregate` query. 
But why this line is not included by default?

**Comment by zag2art** [comment]
I think because of bad performance. Pooling eats quite a lot resources.

**Comment by aliksend** [comment]
Ok, I understood you. Thank you for answer.
