### ISSUE TITLE
Templates: commenting out <xxx:> tag breaks component's template

### ISSUE THREAD

**Issue by aommm** [derbyjs/derby#514]
Whenever this code is present anywhere in a component's template, it breaks:

``` html
<!-- <my-view-here:> test content-->
```

The entire component is then rendered as `">"`, as can be seen when inspecting the generated DOM.

I understand that this is a minor bug, but I thought it worth reporting nonetheless!

**Comment by dadisn** [comment]
Same as #468.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
