### ISSUE TITLE
Chrome plugins can cause attach failed error on client

### ISSUE THREAD

**Issue by droganov** [derbyjs/derby#517]
How to reproduce:
1. Install lingualy chrome [plugin](https://chrome.google.com/webstore/detail/lingualy-practice-a-langu/iilcekgoelpgecpjnnoikhbleipnjdhf?hl=en)
2. Visit derbyjs.com 

![image](https://cloud.githubusercontent.com/assets/1375299/9300751/fdeb2486-44d1-11e5-916f-c9b741e9c0eb.png)

At leat one known chrome plugin can interrupt derby, probably some other can too.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
