### ISSUE TITLE
Sorted collection and server hooks sync problems

### ISSUE THREAD

**Issue by ruimgoncalves** [derbyjs/derby#518]
#### Description

The client that adds a document to a sorted collection may not get back the fields that where changed or populated on the server by a 'submit' or 'after submit' hook.
All other connected clients listening to the same query get the correct data.
###### Client

index.coffee

``` coffeescript
tests = model.query "tests",
  $orderby :
    "_m.ctime" : -1
model.subscribe tests, (err)->
  return next(err) if err
  model.ref "_page.tests", tests
  page.render "home"
```

home.html

``` html
...
<div class="row">
  <div class="col-md-12">
    <ul>
      {{each _page.tests as #test, #idx}}
        <li>{{#idx}} - {{#test.before}} - {{#test.description}} - {{#test.after}}</li>
      {{/each}}
    </ul>
  </div>
</div>
...
```
###### Server

store.coffee

``` coffeescript
dbStore.shareClient.use 'submit', (shareRequest, done)->
  collection = shareRequest.collection
  docId = shareRequest.docName
  opData = shareRequest.opData
  if collection == "tests" && opData.create
    cData = opData.create.data
    cData.before = +new Date
  done()

dbStore.shareClient.use 'after submit', (shareRequest, done)->
  collection = shareRequest.collection
  session = shareRequest.agent.connectSession
  docId = shareRequest.docName
  opData = shareRequest.opData
  backend = shareRequest.backend
  if collection == "tests" && opData.create
    model = dbStore.createModel()
    test = model.at "tests.#{docId}"
    model.fetch test, (err)->
      test.set "after", +new Date
      model.close()
    done()
  else
    done()
```
#### Steps to reproduce the problem

Open 2 browsers and open the dev console in one of them.
Add some documents to the tests collection

``` console
app.model.add('tests', {description : +new Date()})
```
#### What happens

In the client that added some tests, you can see that the **before** field is not populated, the **description** is correctly populated, and the **after** field may or may not be populated. This happens if query is ordered by date descending. If you set an empty query it is correctly populated.
#### Problems

The are 2 distinct problems here.

The **before** field not being displayed is because sharejs doesn't sync the the changed fields on the 'submit' hook. Maybe a sharejs problem / enhancement.

The **after** field not being displayed on the client that added the document, is a timing issue caused by the sort query. Strangely all other connected clients get all correct values changed in the 'after submit' hook

**Comment by ruimgoncalves** [comment]
Adding the following line before https://github.com/share/ShareJS/blob/master/lib/client/doc.js#L947

``` javascript
this.snapshot = this.type.create(msg.create.data);
```
seems to allow the clients to receive the correct data changed in the 'submit' hook. 
This is huge for me, it allows me to add some computed data before inserting it to the database and propagating correctly to all clients. The 'submit' hook is much more efficient than 'after submit', it saves me some round trips to the db.

Of course this is only an hack... and I don't know if it breaks something in the logic.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
