### ISSUE TITLE
Cannot easily set negative values on a bound <input type="number">

### ISSUE THREAD

**Issue by ruimgoncalves** [derbyjs/derby#519]
If there is an input element with type number and a bound value attribute, its not easy to enter a negative value.

If you type a minus char in an empty input field, the text is cleared before you can enter a numeric value.
The only way to insert a negative value is to do it throw the up down buttons or to insert a leading minus after some numbers are already present in the field.

Tested on Firefox.

**Comment by kRaw1er** [comment]
and floats, for example: 3.5

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
