### ISSUE TITLE
Value attribute is removed from option element on second render

### ISSUE THREAD

**Issue by ruimgoncalves** [derbyjs/derby#522]
Having this template fragment

``` html
...
<select id="storeSel" name="store" class="form-control" required>
 <option value="" >(Select One)</option>
 <option value="01" >Store 1</option>
 <option value="02" >Store 2</option>
</select>
...
```

The first time the page is rendered directly from the server, the page is created has expected.
Then in the client if I use app.go("settings"), to display the same page, the generated html is identical, but all the value attributes are removed from the option element.

``` html
<!-- generated after second render -->
...
<select id="storeSel" name="store" class="form-control" required>
 <option >(Select One)</option>
 <option >Store 1</option>
 <option >Store 2</option>
</select>
...
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
