### ISSUE TITLE
View: path[@attribute] fails, path[attribute] works

### ISSUE THREAD

**Issue by michael-brade** [derbyjs/derby#523]
Contrary to the documentation, which says [here](http://derbyjs.com/docs/derby-0.6/components/scope):

> You can always render an attribute in your component's view using {{@attr}}, no matter how it is passed in.

it does not work to use the @-form in an index lookup. I wrote a testcase [here](https://github.com/michael-brade/derby-parsing/commit/8993eb2ebf29796ce4e558e15f9ccea9d7af160b). If you alias the attribute, it works again.

**Comment by michael-brade** [comment]
Actually, `path[attribue]` cannot always be used either:  if it comes from a different controller, and that controller sets it to the result of a controller function, then using just `path[attribute]` will complain about not finding the function. This is really frustrating. Using `{{with @attribute as #attribute}}` is the only solution right now.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
