### ISSUE TITLE
Binding to a textarea does not work

### ISSUE THREAD

**Issue by michael-brade** [derbyjs/derby#524]
Simple case:
```
<textarea id="{{@id}}" class="form-control" value="{{#item[attr.id]}}" />
```
It has no effect when changing the text inside the textarea in the browser. The model doesn't notice. Change `textarea` to `input` and it will work right away.

**Comment by hflw** [comment]
Have you tried writing the whole closing tag out? eg`<textarea></textarea>`

Textarea isn't a self-closing tag so sometimes it's behavior can get strange when writing it that way.

**Comment by michael-brade** [comment]
Well, that sounded exciting... but I just did and it does not change anything. You know, I would fix the bug myself, but I have no idea where to start looking for the binding code in Derby. Anyone with some hints?

**Comment by ishbu** [comment]
Textarea does not take a value. Bind to the inner content instead. 

<text area>{{myValue}}</text area>

**Comment by michael-brade** [comment]
Yay, thank you! I actually just found it at the end of Page.js and wondered why it was looking for parent. Then I saw it in the FAQ... doh!

**Comment by hflw** [comment]
No problem! Glad you got it working :)
