### ISSUE TITLE
return new Function('return ' + message.views)

### ISSUE THREAD

**Issue by janbiasi** [derbyjs/derby#529]
Would be great if you could just replace this line with a good one :+1: :smile_cat: [/lib/App.js#L232](https://github.com/derbyjs/derby/blob/master/lib/App.js#L232). Thanks a lot & great work man!

**Comment by dcbrwn** [comment]
![image](https://cloud.githubusercontent.com/assets/12214069/12922189/73696f96-cf61-11e5-8b8c-b2eebe49281b.png)

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
