### ISSUE TITLE
Textarea placeholder bug

### ISSUE THREAD

**Issue by plusbpm** [derbyjs/derby#531]
In ie10 trying to register the element "textarea" with placeholder attribute is getting an error:
![ie10_placeholder_bug](https://cloud.githubusercontent.com/assets/428403/15291436/90747614-1b86-11e6-93a4-d7c520c9225a.jpg)

**Comment by plusbpm** [comment]
ie11 have same issue

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
