### ISSUE TITLE
Update or Insert Bulk documents like Mongoclient updateMany and insertMany

### ISSUE THREAD

**Issue by kapeskittu** [derbyjs/derby#546]
We want to perform bulk inserts and updates using Racer model like how mongoClient updateMany and insertMany works. Do we have any implementation for this with Racer and Sharedb? If not is there any other way to do a bulk action that will be compatible with Racer and Sharedb?

We tried inserting documents with mongoClient insertMany both in actual collection and o_ collection. Does sharedb recognize inserted documents if we do with this way?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
