### ISSUE TITLE
How to add some external JS with DOM to derby?

### ISSUE THREAD

**Issue by IAkumaI** [derbyjs/derby#557]
For example, when site uses JivoSite or other web-chat script, this script adds some dom elments to body. Button, chat-window etc.

How to save this elements whe derby switch page?
It's just removes from body.

**Comment by balek** [comment]
I think you can just wrap this script into Derby component. But it will be recreated on each page. Is it what you want to avoid?

**Comment by IAkumaI** [comment]
Re-create chat widget on every page change? I don;t this this is good idea :(

Ideal, I want to keep some dom elements whe page is changed.

**Comment by IAkumaI** [comment]
Is there way to keep some elements on the page?

May be...remove them on event and than put it back..

**Comment by zag2art** [comment]
You should use on-create component event. This even emitted only once the element is loaded into dom. It's a regular approach. We wrote a ton of wrappers that way.

**Comment by IAkumaI** [comment]
Thanks, I'll try
