### ISSUE TITLE
Is there template syntax support for JetBains PhpStrom/WebStorm?

### ISSUE THREAD

**Issue by IAkumaI** [derbyjs/derby#558]
JetBains is a popular IDE. Is there any plugin for derbyjs-template syntax support?

**Comment by IAkumaI** [comment]
Well. I created hack for `<derby-Some>` tags. Maybe it will be usefull for someone else.

```
let oldCOmpiler = app.compilers['.html'];

app.compilers['.html'] = function (file, filename) {
    file = file.replace(/(<\/?)derby-(\w+)/g, '$1$2:').replace(/<\/\w+:>/g, '');
    return oldCOmpiler(file, filename);
};
```

Templates may be wrapper into <derby-Body></derby-Body> tag and PhpStorm will not alert errors.

```
<derby-Body>
    <div>Some html here</div>
</derby-Body>
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
