### ISSUE TITLE
[PR] Not possible to set style file for component

### ISSUE THREAD

**Issue by IAkumaI** [derbyjs/derby#562]
Page https://derbyjs.com/docs/derby-0.10/components/structure says that I can set Component.prototype.style and this styles will be loaded. But they don't.

I have created PR to fix this: https://github.com/derbyjs/derby/pull/561

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
