### ISSUE TITLE
Dependencies always override "existing" views

### ISSUE THREAD

**Issue by michael-brade** [derbyjs/derby#571]
It's really great to finally have view dependencies in Derby! However, [this](https://github.com/derbyjs/derby/blob/2819411a7d0b2a4b8ac3bcab7f594a5d0a5d5c27/lib/App.js#L239) exception creates a problem: on the server, everything works and Derby serializes the views, then the client registers the serialized views. After that, the client executes the component code, tries to add the dependencies (again) and throws this error.

I think a solution might be to check if we are in a server context and only then throw this error--unless it is possible to create new view only on the client.

**Comment by ericyhwang** [comment]
I haven't tested out component dependencies in a full app yet, looks like there are still a couple kinks to work out! @nateps 

derby-standalone doesn't use view serialization+deserialization, so a simple "browser?" check may not work for it.

I wonder if it'll work to specifically target the deserialized-views case:
* Detect whether the app has loaded serialized views - the module-level `serializedViews` in App.js looks promising.
* If so, then skip that check if `currentConstructor == null` to allow calling `app.component` over a deserialized view, under the assumption that the server app has validated dependency-loading already.

Side note - Not seeing anything on a serialized view to indicate that it's (de)serialized:
https://github.com/derbyjs/derby-templates/blob/b27df21d15b45ebfb1518810165019f7d8280b2f/lib/templates.js#L526

**Comment by nateps** [comment]
Thanks for flagging. Just published a fix in v0.10.24. Let us know if that works!
