### ISSUE TITLE
Is there any method for build-only scripts?

### ISSUE THREAD

**Issue by IAkumaI** [derbyjs/derby#578]
Building (bundling) app scripts has much time (about minute) and cpu cost. If i run derby in k8s with replicas more than 1, in fact, I don't need to bundle app on each run. I can build app, put .js files in the container and just run container.

So, i tried to bundle scripts once and then just start derby application.

But if i do not call app.writeScripts method, app.scriptUrl is null, so application does not know script url.

It there any workaround to bundle scripts indepenedence of app run?

**Comment by ericyhwang** [comment]
Yes, though I don't think it's documented at the moment.

`app.writeScripts()` produces the JS bundle, then `app.serialize()` method produces a `.json` and `.views.js` file for the app, which `AppForServer#_initViews` looks for.

So you might have a pack.js like this that your Dockerfile can call:

```js
function packApp(app, cb) {
  app.writeScripts(backend, SERVER_PUBLIC_DIR, options, (error) => {
    if (error) return cb(error);
    app.serialize();
    cb();
  });
}

const app = require('/path/to/derby/app');
packApp(app, (error) => {
  if (error) {
    console.error(`Error packing app ${app.filename}:`, error);
    process.exit(1);
  } else {
    console.error(`Done packing app ${app.filename}`);
  }
});
```

Adapt to your setup as needed. It should be able to work in parallel for multiple Derby apps with different names, too.
