### ISSUE TITLE
Pull request in derby-site

### ISSUE THREAD

**Issue by ile** [derbyjs/derby#624]
Fyi, there is a pull request here: https://github.com/derbyjs/derby-site/pull/65

**Comment by ile** [comment]
Are you going to just ignore this, because apparently you don't like me for some reason? Can I ask why?

**Comment by ile** [comment]
Wouldn't you want to showcase software made with Derby?

If you want to ignore me, close the issue/pull-request.

**Comment by craigbeck** [comment]
merged
